### PR TITLE
remove unnecessary code

### PR DESCRIPTION
**Pull request by dangilman**

### CODE REVIEW

**Comment by dangilman** [comment]
Sure, how do I test that a specific line raises a ValueError? 

- Daniel

**Comment by sibirrer** [comment]
> Sure, how do I test that a specific line raises a ValueError? - Daniel
> […](#)

there are specific raise test functions. You can look for examples in tests of other classes, such as in test/test_Data/test_imaging_data.py as an example.

**Comment by sibirrer** [comment]
Thanks! So the Optimizer module is at 96.15% test coverage. If you can bring it above 97% that'd be good. You can see what lines are tested here:
https://coveralls.io/builds/32307679
Sorry to be obnoxious here, as usage of lenstronomy increases, I want to make sure there is as good a testing as possible.

**Comment by dangilman** [comment]
I removed some untested lines that were inaccessible anyways (I don't remember adding them myself)

**Comment by sibirrer** [comment]
> I removed some untested lines that were inaccessible anyways (I don't remember adding them myself)

so the set_static() and set_dynamic() calls can speed up lens equation solving under fixed parameters of the mass profiles (as it stores some re-ocurant quantities in cache for some lens models). I added it as an option in this code to allow to make you use it.

**Comment by sibirrer** [comment]
thanks! up to you to plug back in the set_static and set_dynamic calls. Otherwise I am happy to approve the PR. Just let me know.

**Comment by dangilman** [comment]
Yeah you can leave them out

**Pull request merged**
