### PR TITLE
Fix bug where lens equation solving parameters are not updated

### PR DESCRIPTION
**Pull request by ewoudwempe**
This fixes the lens equation solving parameter update routine that did not work because `hasattr` does not test for dictionary keys (e.g. `hasattr({'a':1},a)` returns False).

### CODE REVIEW

**Review by sibirrer — CHANGES_REQUESTED** [review]
Thank you! I'll wait until the continuous integration tests are run. I have one request though: Can you add your name on the contributors list? :) https://github.com/sibirrer/lenstronomy/blob/master/AUTHORS.rst

**Comment by ewoudwempe** [comment]
Done :)

**Comment by sibirrer** [comment]
Thanks :) Travis-CI is slow (and I need to move to GitHub Actions anyways). Will merge it as soon as Travis-CI passes. This might take a while, sorry about that.

**Comment by sibirrer** [comment]
Test coverage impact not caused by this PR. Will be merged. Thank you very much!

**Pull request merged**
