### PR TITLE
Optimizer class

### PR DESCRIPTION
**Pull request by dangilman**
all tests should pass now

### CODE REVIEW

**Comment by sibirrer** [comment]
Hi Daniel,

do you see the error message with python3? I think in python3 you need to import the entire path form the package, e.g. from lenstronomy.Subpackage….

And the error message in python2 comes from the fact that the ‚SPEMD‘ model is not properly installed (as it requires fastell, a fortran code which is not possible to be tested in a python environment). So the ‚SPEMD‘ routine returns a lot of zeros/Nones (I coded it up that way). You can use the ‚SPEP‘ (ellipticity in the potential) and it should work, with a bit different values.

Let me know if you have questions.

Cheers,
Simon

On 31 Jul 2018, at 10:28, dangilman <notifications@github.com> wrote:

all tests should pass now

You can view, comment on, or merge this pull request online at:

  https://github.com/sibirrer/lenstronomy/pull/14 <https://github.com/sibirrer/lenstronomy/pull/14>
Commit Summary

optimizer class
optimizer class
edited test
File Changes

A lenstronomy/LensModel/Optimizer/PSO_optimizer.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-0> (199)
A lenstronomy/LensModel/Optimizer/__init__.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-1> (0)
A lenstronomy/LensModel/Optimizer/multi_plane.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-2> (411)
A lenstronomy/LensModel/Optimizer/optimizer.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-3> (175)
A lenstronomy/LensModel/Optimizer/params.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-4> (227)
A lenstronomy/LensModel/Optimizer/single_plane.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-5> (176)
M lenstronomy/Util/util.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-6> (24)
A test/test_LensModel/test_Optimizer/__init__.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-7> (0)
A test/test_LensModel/test_Optimizer/test_multi_plane.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-8> (79)
A test/test_LensModel/test_Optimizer/test_single_plane.py <https://github.com/sibirrer/lenstronomy/pull/14/files#diff-9> (67)
Patch Links:

https://github.com/sibirrer/lenstronomy/pull/14.patch <https://github.com/sibirrer/lenstronomy/pull/14.patch>
https://github.com/sibirrer/lenstronomy/pull/14.diff <https://github.com/sibirrer/lenstronomy/pull/14.diff>

**Comment by sibirrer** [comment]
You're almost there. Python 3.4 for some reason strikes:
https://travis-ci.org/sibirrer/lenstronomy/jobs/411903297
If you look at the coverall report, some of your parts are only tested to < 80% tested which drops the overall test coverage of lenstronomy. Maybe writing a few tests about routines that have no test coverage would help. Thank you!

**Comment by dangilman** [comment]
I don't understand why the second build fails... 

I can add some more tests

**Comment by sibirrer** [comment]
don't you want to change the 'SPEMD' into a 'SPEP' model for testing as I can not guarantee a well defined output of 'SPEMD' on the testing platform.

**Comment by dangilman** [comment]
hmm I don't see anywhere in the test routines where I use a spemd model, do you see something else?

**Comment by dangilman** [comment]
HURRAH

**Pull request merged**
